name: Build & test

on:
  push:
    branches:
      - 'master'
      - 'main'
  pull_request_target:
    branches:
      - 'master'
      - 'main'

jobs:
  php:
    name: PHP test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.4']
        wp: ['6.3']
        mysql: ['5.7']
    services:
      mysql:
        image: mysql:${{ matrix.mysql }}
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, dom, simplexml
          tools: wp
      - uses: actions/checkout@v3
        with:
          path: wp-content/plugins/ll-site-health-filter
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Debugging
        run: |
          php --version
          php -m
          composer --version
      - name: Composer build
        run: |
          cd wp-content/plugins/ll-site-health-filter
          composer config --global --auth http-basic.repo.packagist.com token "${{ secrets.PRIVATE_PACKAGIST_TOKEN }}"
          composer install --prefer-dist
        env:
          PRIVATE_PACKAGIST_TOKEN: ${{ secrets.PRIVATE_PACKAGIST_TOKEN }}
      - name: test:composer
        run: |
          cd wp-content/plugins/ll-site-health-filter
          composer run test:composer
      - name: test:phpcs
        run: |
          cd wp-content/plugins/ll-site-health-filter
          composer run test:phpcs
      - name: test:docs
        run: |
          cd wp-content/plugins/ll-site-health-filter
          composer run test:docs
